// src/components/SystemCard.tsx
// src/components/SystemCard.tsx
import React from "react";
import { FaChevronDown, FaChevronUp } from "react-icons/fa";
// Import all relevant interfaces from systemSpecs.ts
import { SystemDetails, MonitorDetail } from "../data/systemSpecs";

interface SystemCardProps extends React.JSX.IntrinsicAttributes {
  system: SystemDetails;
  // New Props for controlled state
  isExpanded: boolean; // Tells the card if it should be open
  onToggle: (systemId: string) => void; // Function to call when header is clicked
}

interface ListItem {
  label: string;
  value: string | MonitorDetail[];
  notes?: string;
  link?: string;
}

const ItemList: React.FC<{ items: ListItem[] }> = ({ items }) => (
  // ... (ItemList component remains unchanged)
  <div className="item-list">
    {items.map((item, index) => (
      <div
        key={`${item.label}-${index}`}
        className="item-list__item"
      >
        <span className="item-list__label">
          {item.label}:
        </span>
        <span className="item-list__value">
          {Array.isArray(item.value) ? (
            <ul className="monitor-list">
              {item.value.map((monitor, i) => (
                <li key={i}>
                  {monitor.model}
                  {monitor.role && ` (${monitor.role})`}
                  {monitor.size && `, ${monitor.size}`}
                  {monitor.refreshRate && `, ${monitor.refreshRate}`}
                  {monitor.notes && (
                    <span className="monitor-list__note">
                      ({monitor.notes})
                    </span>
                  )}
                  {monitor.link && typeof monitor.link === "string" && (
                    <a
                      href={monitor.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="monitor-list__link"
                    >
                      [Link]
                    </a>
                  )}
                </li>
              ))}
            </ul>
          ) : (
            item.value
          )}
          {item.notes && typeof item.value === "string" && (
            <span className="item-list__note">
              ({item.notes})
            </span>
          )}
          {item.link && typeof item.value === "string" && (
            <a
              href={item.link}
              target="_blank"
              rel="noopener noreferrer"
              className="item-list__link"
            >
              [Link]
            </a>
          )}
        </span>
      </div>
    ))}
  </div>
);


const SystemCard: React.FC<SystemCardProps> = ({ system, isExpanded, onToggle }) => {
  // We need a unique ID for this system to pass back to the parent
  const systemId = system.name.replace(/\s/g, "-");
  
  // Call the onToggle function from props, passing this card's ID
  const handleCardToggle = () => {
    onToggle(systemId);
  };

  const contentId = `system-specs-content-${systemId}`;
  const expandedClass = isExpanded ? "system-card__content--expanded" : "system-card__content--collapsed";

  return (
    <section className="system-card">
      <button
        type="button"
        // Use the new handler which calls the parent's function
        onClick={handleCardToggle}
        className="system-card__header-btn"
        aria-expanded={isExpanded}
        aria-controls={contentId}
      >
        <h3 className="system-card__title">{system.name}</h3>
        <span className="system-card__toggle-icon">
          {isExpanded ? (
            <FaChevronUp size="1em" />
          ) : (
            <FaChevronDown size="1em" />
          )}
        </span>
      </button>

      {system.description && (
        <p className="system-card__description">{system.description}</p>
      )}

      <div
        id={contentId}
        className={`system-card__content ${expandedClass}`}
      >
        <div className="system-card__inner-content">
          {/* Core PC Specifications Section */}
          { system.specs && system.specs.length > 0 && (
            <>
              <h4 className="system-card__section-header">
                Core PC Specifications
              </h4>
              <ItemList items={system.specs} />
            </>
          )}

          { system.accessories && system.accessories.length > 0 && (
            <>
              <h4 className="system-card__section-header">
                Accessories
              </h4>
              <ItemList items={system.accessories} />
            </>
          )}
          
          {/* Peripherals Section (conditionally rendered) */}
          {system.peripherals && system.peripherals.length > 0 && (
            <>
              <h4 className="system-card__section-header peripheral-section">
                Peripherals
              </h4>
              <ItemList items={system.peripherals} />
            </>
          )}
          
          {/* Software & Operating Systems Section (conditionally rendered) */}
          {system.softwareAndOS && system.softwareAndOS.length > 0 && (
            <>
              <h4 className="system-card__section-header peripheral-section">
                Software & Operating Systems
              </h4>
              <ItemList items={system.softwareAndOS} />
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default SystemCard;

// src/lib/components/SystemCard.svelte
<script lang="ts">
  import type { SystemDetails, MonitorDetail } from "$lib/data/systemSpecs";

  let {
    system,
    isOpen = false,
    onToggle,
  }: {
    system: SystemDetails;
    isOpen?: boolean;
    onToggle?: () => void;
  } = $props();

  function handleToggle() {
    if (onToggle) {
      onToggle();
    }
  }

  function isMonitorArray(
    value: string | MonitorDetail[],
  ): value is MonitorDetail[] {
    return Array.isArray(value);
  }
</script>

<div class="system-card">
  <div class="system-card-header">
    <span class="system-card-title">{system.name}</span>
    <button class="system-card-toggle" onclick={handleToggle}>
      {isOpen ? "▼" : "▶"}
    </button>
  </div>

  {#if system.description}
    <p class="system-card-description">{system.description}</p>
  {/if}

  {#if isOpen}
    <div class="system-card-specs">
      {#if system.specs}
        {#each system.specs as spec}
          <div class="system-card-spec">
            <span class="system-card-spec-label">{spec.label}</span>
            <span class="system-card-spec-value">
              {#if spec.link}
                <a href={spec.link} target="_blank">{spec.value}</a>
              {:else}
                {spec.value}
              {/if}
              {#if spec.notes}
                <br /><small>({spec.notes})</small>
              {/if}
            </span>
          </div>
        {/each}
      {/if}

      {#if system.peripherals}
        {#each system.peripherals as peripheral}
          <div class="system-card-spec">
            <span class="system-card-spec-label">{peripheral.label}</span>
            <span class="system-card-spec-value">
              {#if isMonitorArray(peripheral.value)}
                {#each peripheral.value as monitor}
                  <div>
                    {#if monitor.link}
                      <a href={monitor.link} target="_blank">{monitor.model}</a>
                    {:else}
                      {monitor.model}
                    {/if}
                    {#if monitor.role}
                      ({monitor.role}){/if}
                    {#if monitor.size}
                      - {monitor.size}{/if}
                    {#if monitor.refreshRate}
                      @ {monitor.refreshRate}{/if}
                  </div>
                {/each}
              {:else if peripheral.link}
                <a href={peripheral.link} target="_blank">{peripheral.value}</a>
              {:else}
                {peripheral.value}
              {/if}
            </span>
          </div>
        {/each}
      {/if}

      {#if system.accessories}
        {#each system.accessories as accessory}
          <div class="system-card-spec">
            <span class="system-card-spec-label">{accessory.label}</span>
            <span class="system-card-spec-value">
              {#if accessory.link}
                <a href={accessory.link} target="_blank">{accessory.value}</a>
              {:else}
                {accessory.value}
              {/if}
              {#if accessory.notes}
                <br /><small>({accessory.notes})</small>
              {/if}
            </span>
          </div>
        {/each}
      {/if}

      {#if system.softwareAndOS}
        {#each system.softwareAndOS as software}
          <div class="system-card-spec">
            <span class="system-card-spec-label">{software.label}</span>
            <span class="system-card-spec-value">
              {software.value}
              {#if software.notes}
                <br /><small>({software.notes})</small>
              {/if}
            </span>
          </div>
        {/each}
      {/if}
    </div>
  {/if}
</div>
